### ISSUE TITLE
`flutter run` results in : `Warning: Podfile is out of date` error

### ISSUE THREAD

**Issue by grokify** [grokify/Agora-Flutter-Quickstart#4]
```
% flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Upgrading contents.xcworkspacedata
Updating minimum iOS deployment target from 8.0 to 9.0.
Upgrading project.pbxproj
Upgrading AppFrameworkInfo.plist
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS or macOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:

  rm ios/Podfile


Error launching application on iPhone 12 Pro Max.
```

**Comment by geetansh-monga** [comment]
let me raise a pull request after fixing it.
working in issue #1

**Comment by grokify** [comment]
After `rm ios/Podfile`:

```
% rm ios/Podfile
% flutter run   
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                            101.3s
Running Xcode build...                                                  
Xcode build done.                                           47.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
<...>
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 14.4.99. (in target 'AgoraRtcEngine_iOS' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

Grep for `IPHONEOS_DEPLOYMENT_TARGET` returns both 9.0 and 8.0, with some 9.0 likely being updated from the previous `flutter run`.

```
% grep -iR IPHONEOS_DEPLOYMENT_TARGET *
ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
ios/.symlinks/plugins/agora_rtc_engine/example/ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
ios/.symlinks/plugins/agora_rtc_engine/example/ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
ios/.symlinks/plugins/agora_rtc_engine/example/ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
ios/.symlinks/plugins/permission_handler/example/ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/.symlinks/plugins/permission_handler/example/ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
ios/.symlinks/plugins/permission_handler/example/ios/Runner.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
```

**Comment by grokify** [comment]
Updating all `IPHONEOS_DEPLOYMENT_TARGET` items from the previous `grep` to 9.0 results in the following:

```
% flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                           2,388ms
Running Xcode build...                                                  
Xcode build done.                                            8.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ld: building for iOS Simulator, but linking in dylib built for iOS, file
    '.../Agora-Flutter-Quickstart/ios/Pods/AgoraRtcEngine_iOS/AgoraDav1dExtension.framework/AgoraDav1d
    Extension' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 14.4.99. (in target 'AgoraRtcEngine_iOS' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

`ios/Podfile` starts with the following. Uncommenting this line does not change the `flutter run` behavior.

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
```

**Comment by grokify** [comment]
Next step:

1. [Xcode 12 drops support for iOS 8 and how to fix deployment target warnings in CocoaPods](https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/)
1. [The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.](https://github.com/firebase/firebase-ios-sdk/issues/6533)

Updating `ios/Podfile` from:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

to:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
    flutter_additional_ios_build_settings(target)
  end
end
```

results in the following:

```bash
 % flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                              4.0s
Running Xcode build...                                                  
Xcode build done.                                            8.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ld: building for iOS Simulator, but linking in dylib built for iOS, file
    '.../Agora-Flutter-Quickstart/ios/Pods/AgoraRtcEngine_iOS/AgoraDav1dExtension.framework/AgoraDav1d
    Extension' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

`flutter run -v` returns the following...

```bash
<...>
[  +62 ms] Could not build the application for the simulator.
[   +1 ms] Error launching application on iPhone 12 Pro Max.
[   +3 ms] "flutter run" took 26,123ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +202 ms] ensureAnalyticsSent: 201ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by grokify** [comment]
References:

1. [Error launching application on iPhone 12 Pro Max](https://github.com/flutter/flutter/issues/69632)
1. [Could not build the application for the simulator. Error launching application on iPhone 11 Pro Max](https://stackoverflow.com/questions/59921997/could-not-build-the-application-for-the-simulator-error-launching-application-o)

Solution didn't work:

The following did not solve the issue:

> 1. Setting platform to 10.0 inside the Podfile (platform :ios, '10.0' )
> 1. Doing a combination of flutter clean, pod cache clean --all and pod install
> 1. Opening the project inside XCode
> 1. Only after doing the last step, flutter run was working fine again.
